#! /bin/bash
# interactive version of run

trap "exit;" SIGINT SIGTERM

while true
do
    ${ANDROID_BUILD_TOP}/system/bt/gd/cert/run "$@"
    python3 ${ANDROID_BUILD_TOP}/system/bt/gd/cert/change_waiter.py ${ANDROID_BUILD_TOP}/system/bt
done
